import { QrCode, Award, Users2, BellRing, ShieldCheck, Zap } from "lucide-react";

export const BENTO_FEATURES = [
  {
    id: "qr-pass",
    title: "Instant QR Smart Pass",
    description: "Encrypted QR passes issued in real time with dynamic validity checks and offline access for frictionless gate entry.",
    icon: QrCode,
    badge: "GATE ENGINE",
    gradient: "from-blue-600 to-indigo-600",
    cols: "lg:col-span-8",
    highlight: "99.8% Faster Gate Entry",
  },
  {
    id: "squads",
    title: "Multi-Disciplinary Squads",
    description: "Create hackathon and sports squads with instant invite codes and cross-department team management.",
    icon: Users2,
    badge: "TEAM BUILDER",
    gradient: "from-purple-600 to-pink-600",
    cols: "lg:col-span-4",
    highlight: "Cross-Dept Ready",
  },
  {
    id: "certificates",
    title: "Tamper-Proof Digital E-Certificates",
    description: "Faculty-authorized certificates generated automatically upon attendance mark. Verifiable online with unique serial hashes.",
    icon: Award,
    badge: "ACCREDITED",
    gradient: "from-amber-500 to-orange-600",
    cols: "lg:col-span-4",
    highlight: "NAAC Verified",
  },
  {
    id: "realtime",
    title: "Live Capacity & Broadcast Alerts",
    description: "Automated queue tracking, real-time waitlists, and instant in-app/email alerts for venue changes or schedule updates.",
    icon: BellRing,
    badge: "LIVE SYNC",
    gradient: "from-emerald-500 to-teal-600",
    cols: "lg:col-span-4",
    highlight: "Sub-Second Updates",
  },
  {
    id: "faculty-tools",
    title: "Faculty & Coordinator Control Hub",
    description: "Real-time registration rosters, QR attendance scanner app, spot registration desks, and analytics export.",
    icon: ShieldCheck,
    badge: "ADMIN SUITE",
    gradient: "from-blue-700 to-cyan-600",
    cols: "lg:col-span-4",
    highlight: "Role-Based Access",
  },
];
